/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */


typedef struct {
	unsigned long long _field1;
	unsigned long long _field2;
} CDAnonymousStruct1;

typedef struct {
} CDAnonymousStruct2;

typedef struct {
	unsigned int bold:1;
	unsigned int dim:1;
	unsigned int underline:1;
	unsigned int inverted:1;
	unsigned int blink:1;
	unsigned int invisible:1;
	unsigned int tab:1;
	unsigned int marked:1;
	unsigned int custom:1;
	unsigned long long ansiForegroundColor;
	unsigned long long ansiBackgroundColor;
} CDAnonymousStruct3;

typedef struct {
	unsigned long long _field1;
	unsigned long long _field2;
	unsigned long long _field3;
	char *_field4;
	unsigned long long _field5;
	unsigned long long _field6;
} CDAnonymousStruct5;

typedef struct {
	unsigned long long y;
	unsigned long long x;
} CDAnonymousStruct4;

typedef struct {
	unsigned long long line;
	unsigned long long column;
} CDAnonymousStruct6;

typedef struct {
	unsigned long long _field1;
	struct {
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned int :1;
		unsigned long long _field1;
		unsigned long long _field2;
	} _field2;
} CDAnonymousStruct7;

typedef struct {
	unsigned short _field1;
	CDAnonymousStruct2 *_field2;
	unsigned int _field3;
} CDAnonymousStruct8;
