/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>
#import "TTView.h"

@interface TTTableView
{
	NSString *_emptyMessage;
}

- (void)dealloc;
- (id)emptyMessageAttributes;
- (id)emptyMessage;
- (void)setEmptyMessage:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

@interface TTAppPrefsController <NSWindowDelegate>
{
	NSMatrix *_defaultShellMatrix;
	NSTextField *_defaultShellTextField;
	NSTabView *_tabView;
	NSArrayController *_profilesController;
	NSArrayController *_workspacesController;
	NSTableView *_profilesTableView;
	NSMenuItem *_profilesActionMenuItem;
	TTTableView *_workspacesTableView;
	NSMenuItem *_workspacesActionMenuItem;
	NSView *_fontAccessoryView;
	BOOL _wasFontPanelVisible;
	BOOL _wasColorPanelVisible;
	NSUndoManager *_undoManager;
	TTView *_thumbnailView;
	TTLogicalScreen *_thumbnailScreen;
}

+ (id)sharedPreferencesController;
- (id)init;
- (void)dealloc;
- (void)applicationWillTerminate:(id)arg1;
- (void)windowDidLoad;
- (id)windowWillReturnUndoManager:(id)arg1;
- (id)undoManager;
- (void)showWindow:(id)arg1;
- (void)commitChanges;
- (void)windowDidResignKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)update;
- (void)defaultShellChanged:(id)arg1;
- (void)showEncodingCustomizationPane:(id)arg1;
- (void)orderFrontFontPanel:(id)arg1;
- (id)profilesController;
- (id)selectedPaneIdentifier;
- (void)setSelectedPaneIdentifier:(id)arg1;
- (void)tabView:(id)arg1 willSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)takeSelectedTabIndexFromToolbarItem:(id)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarSelectableItemIdentifiers:(id)arg1;
- (id)thumbnailView;
- (id)thumbnailOfSize:(struct CGSize)arg1 forProfile:(id)arg2;
- (void)changeFont:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)tableViewDoubleClick:(id)arg1;

@end
